StarWar.create!([
  {character: "Bail Organa", planet: "Kamino", quote: "Strike me down, and I will become more powerful than you could possibly imagine.", droid: "ASP", vehicle: "X-Wing Fighter"},
  {character: "Han Solo", planet: "Dagobah", quote: "Truly wonderful, the mind of a child is.", droid: "GNK", vehicle: "Death Star"},
  {character: "Bail Organa", planet: "Takodana", quote: "Judge me by my size, do you?", droid: "R2-Q5", vehicle: "ATT Battle Tank"},
  {character: "Darth Maul", planet: "Kamino", quote: "Would somebody get this big walking carpet out of my way?", droid: "2-1B", vehicle: "Flash Speeder"},
  {character: "Chewbacca", planet: "Jakku", quote: "Well, you said you wanted to be around when I made a mistake.", droid: "BB-8", vehicle: "Imperial Star Destroyer"},
  {character: "Rune Haako", planet: "Naboo", quote: "You know, that little droid is going to cause me a lot of trouble.", droid: "B4-D4", vehicle: "Republic Cruiser"},
  {character: "Bail Organa", planet: "Kamino", quote: "I have a bad feeling about this.", droid: "2-1B", vehicle: "ATT Battle Tank"},
  {character: "Ben Solo", planet: "Bespin", quote: "Fear is the path to the dark side... fear leads to anger... anger leads to hate... hate leads to suffering.", droid: "ID9", vehicle: "TIE Bomber"},
  {character: "Count Dooku", planet: "Coruscant", quote: "I have a bad feeling about this.", droid: "BD-3000", vehicle: "Republic Cruiser"},
  {character: "Padme Amidala", planet: "Kamino", quote: "A Jedi uses the Force for knowledge and defense, never for attack.", droid: "B2-RP", vehicle: "Imperial Star Destroyer"},
  {character: "Mace Windu", planet: "Kamino", quote: "Do. Or do not. There is no try.", droid: "2-1B", vehicle: "AT-ST Walker"},
  {character: "Count Dooku", planet: "Naboo", quote: "Bounty hunters! We don't need this scum.", droid: "327-T", vehicle: "AT-ST Walker"},
  {character: "Jar Jar Binks", planet: "Dagobah", quote: "Adventure. Excitement. A Jedi craves not these things.", droid: "BD-3000", vehicle: "Vulture Droid"},
  {character: "Ben Solo", planet: "Endor", quote: "Wars not make one great.", droid: "ID9", vehicle: "Imperial Shuttle"},
  {character: "Kylo Ren", planet: "Hosnian Prime", quote: "You do have your moments. Not many, but you have them.", droid: "4-LOM", vehicle: "AT-ST Walker"},
  {character: "Leia Organa", planet: "Sullust", quote: "I have a bad feeling about this.", droid: "FA-4", vehicle: "Sith Infiltrator"},
  {character: "Obi-Wan Kenobi", planet: "Kamino", quote: "No reward is worth this.", droid: "R2-Q5", vehicle: "TIE Bomber"},
  {character: "Sheev Palpatine", planet: "DQar", quote: "No reward is worth this.", droid: "B1", vehicle: "Millennium Falcon"},
  {character: "Nute Gunray", planet: "Takodana", quote: "No reward is worth this.", droid: "C-3PO", vehicle: "Millennium Falcon"},
  {character: "Padme Amidala", planet: "Yavin", quote: "Now, witness the power of this fully operational battle station.", droid: "2-1B", vehicle: "TIE Bomber"},
  {character: "Jar Jar Binks", planet: "Yavin", quote: "Never tell me the odds!", droid: "B4-D4", vehicle: "Death Star"},
  {character: "Darth Caedus", planet: "Naboo", quote: "Now, witness the power of this fully operational battle station.", droid: "B1", vehicle: "X-Wing Fighter"},
  {character: "Mace Windu", planet: "Lothal", quote: "Truly wonderful, the mind of a child is.", droid: "2-1B", vehicle: "AT-AT Walker"},
  {character: "Han Solo", planet: "Takodana", quote: "You will never find a more wretched hive of scum and villainy. We must be cautious.", droid: "BB-8", vehicle: "Sith Infiltrator"},
  {character: "Padme Amidala", planet: "Dagobah", quote: "If they follow standard Imperial procedure, they'll dump their garbage before they go to light-speed.", droid: "B2-RP", vehicle: "Imperial Star Destroyer"},
  {character: "Wedge Antilles", planet: "Yavin", quote: "Aren't you a little short for a Stormtrooper?", droid: "11-4D", vehicle: "V-Wing Fighter"},
  {character: "Luke Skywalker", planet: "Tatooine", quote: "Bounty hunters! We don't need this scum.", droid: "B1", vehicle: "TIE Interceptor"},
  {character: "Anakin Skywalker", planet: "Kamino", quote: "That is why you fail.", droid: "ASP", vehicle: "AT-ST Walker"},
  {character: "Poe Dameron", planet: "Yavin", quote: "You'll find I'm full of surprises!", droid: "LM-432", vehicle: "Speeder Bike"},
  {character: "Sheev Palpatine", planet: "Alderaan", quote: "You know, that little droid is going to cause me a lot of trouble.", droid: "ASP", vehicle: "Trade Federation Battleship"},
  {character: "Lando Calrissian", planet: "Lothal", quote: "Well, you said you wanted to be around when I made a mistake.", droid: "NR-N99", vehicle: "Naboo Royal Starship"},
  {character: "Jango Fett", planet: "Jakku", quote: "No reward is worth this.", droid: "2-1B", vehicle: "Republic Cruiser"},
  {character: "Lando Calrissian", planet: "Endor", quote: "R2-D2, you know better than to trust a strange computer!", droid: "ASP", vehicle: "TIE Interceptor"},
  {character: "Darth Maul", planet: "Yavin", quote: "That is why you fail.", droid: "R2-Q5", vehicle: "Imperial Shuttle"},
  {character: "Darth Maul", planet: "Dagobah", quote: "Who's the more foolish; the fool, or the fool who follows him?", droid: "2-1B", vehicle: "Imperial Shuttle"},
  {character: "Sebulba", planet: "Mustafar", quote: "Would somebody get this big walking carpet out of my way?", droid: "B1", vehicle: "TIE Interceptor"},
  {character: "Sebulba", planet: "Yavin", quote: "Judge me by my size, do you?", droid: "2-1B", vehicle: "Gungan Bongo Submarine"},
  {character: "Chewbacca", planet: "Bespin", quote: "Who's the more foolish; the fool, or the fool who follows him?", droid: "B2-RP", vehicle: "Imperial Star Destroyer"},
  {character: "Panaka", planet: "Kamino", quote: "You do have your moments. Not many, but you have them.", droid: "GNK", vehicle: "X-Wing Fighter"},
  {character: "Mace Windu", planet: "Lothal", quote: "If you're saying that coming here was a bad idea, I'm starting to agree with you.", droid: "B1", vehicle: "Republic Cruiser"},
  {character: "Darth Vader", planet: "Geonosis", quote: "That is why you fail.", droid: "GH-7", vehicle: "Imperial Shuttle"},
  {character: "Panaka", planet: "Tatooine", quote: "Truly wonderful, the mind of a child is.", droid: "GH-7", vehicle: "Gungan Bongo Submarine"},
  {character: "Ki-Adi-Mundi", planet: "Kamino", quote: "Fear is the path to the dark side... fear leads to anger... anger leads to hate... hate leads to suffering.", droid: "327-T", vehicle: "AT-ST Walker"},
  {character: "Watto", planet: "Kashyyyk", quote: "Do. Or do not. There is no try.", droid: "4-LOM", vehicle: "Imperial Shuttle"},
  {character: "Padme Amidala", planet: "Dagobah", quote: "If you're saying that coming here was a bad idea, I'm starting to agree with you.", droid: "BB-8", vehicle: "Republic Cruiser"},
  {character: nil, planet: nil, quote: nil, droid: nil, vehicle: nil},
  {character: nil, planet: nil, quote: nil, droid: nil, vehicle: nil},
  {character: "JW", planet: "Hoth", quote: "It is a dark time for the Rebellion.", droid: "CC-6", vehicle: "Snowspeeder"},
  {character: "JW", planet: "Tattooine", quote: "It's either a big dark blur or a big light blur.", droid: "CC-6", vehicle: nil},
  {character: "JW", planet: "Tattooine", quote: "It's either a big dark blur or a big light blur.", droid: "CC-6", vehicle: nil},
  {character: "JW", planet: "Tattooine", quote: "It's either a big dark blur or a big light blur.", droid: "CC-6", vehicle: nil},
  {character: "Ki-Adi-Mundi", planet: "Yavin", quote: "You are unwise to lower your defenses!", droid: "4-LOM", vehicle: nil},
  {character: "Bib Fortuna", planet: "Tattooine", quote: "It's either a big dark blur or a big light blur.", droid: "JW-M2", vehicle: nil},
  {character: "Count Dooku", planet: "Bespin", quote: "If you're saying that coming here was a bad idea, I'm starting to agree with you.", droid: "FA-4", vehicle: "X-Wing Fighter"},
  {character: "Darth Caedus", planet: "Sullust", quote: "Only at the end do you realize the power of the Dark Side.", droid: "GNK", vehicle: "Death Star"},
  {character: "Sheev Palpatine", planet: "Mustafar", quote: "Do. Or do not. There is no try.", droid: "327-T", vehicle: "Death Star"},
  {character: "Jango Fett", planet: "Naboo", quote: "No reward is worth this.", droid: "11-4D", vehicle: "X-Wing Fighter"},
  {character: "Bail Organa", planet: "Alderaan", quote: "Bounty hunters! We don't need this scum.", droid: "327-T", vehicle: "Flash Speeder"},
  {character: "Kylo Ren", planet: "Mustafar", quote: "Who's the more foolish; the fool, or the fool who follows him?", droid: "C-3PO", vehicle: "Naboo Royal Starship"},
  {character: "Nute Gunray", planet: "Takodana", quote: "You do have your moments. Not many, but you have them.", droid: "C-3PO", vehicle: "Trade Federation Battleship"},
  {character: "Panaka", planet: "Mustafar", quote: "You know, that little droid is going to cause me a lot of trouble.", droid: "FA-4", vehicle: "Flash Speeder"},
  {character: "Bail Organa", planet: "Takodana", quote: "Wars not make one great.", droid: "LM-432", vehicle: "V-Wing Fighter"},
  {character: "Panaka", planet: "Endor", quote: "You'll find I'm full of surprises!", droid: "FA-4", vehicle: "Sandcrawler"},
  {character: "Han Solo", planet: "Lothal", quote: "I have a bad feeling about this.", droid: "B1", vehicle: "Gungan Bongo Submarine"},
  {character: "Sheev Palpatine", planet: "Alderaan", quote: "You know, that little droid is going to cause me a lot of trouble.", droid: "B1", vehicle: "TIE Interceptor"},
  {character: "Kylo Ren", planet: "Yavin", quote: "If they follow standard Imperial procedure, they'll dump their garbage before they go to light-speed.", droid: "GNK", vehicle: "Sith Infiltrator"},
  {character: "Qui-Gon Jinn", planet: "Alderaan", quote: "You know, that little droid is going to cause me a lot of trouble.", droid: "B2-RP", vehicle: "Naboo N-1 Starfighter"},
  {character: "Obi-Wan Kenobi", planet: "Coruscant", quote: "Fear is the path to the dark side... fear leads to anger... anger leads to hate... hate leads to suffering.", droid: "2-1B", vehicle: "Republic Cruiser"},
  {character: "Wedge Antilles", planet: "Alderaan", quote: "Adventure. Excitement. A Jedi craves not these things.", droid: "ASP", vehicle: "Sandcrawler"},
  {character: "Borvo the Hutt", planet: "Lothal", quote: "Never tell me the odds!", droid: "LM-432", vehicle: "Imperial Shuttle"},
  {character: "Darth Maul", planet: "Kamino", quote: "Now, witness the power of this fully operational battle station.", droid: "GH-7", vehicle: "Naboo Royal Starship"},
  {character: "Darth Maul", planet: "Naboo", quote: "Only at the end do you realize the power of the Dark Side.", droid: "GH-7", vehicle: "Vulture Droid"},
  {character: "Mace Windu", planet: "Alderaan", quote: "That is why you fail.", droid: "BD-3000", vehicle: "Naboo Royal Starship"},
  {character: "Count Dooku", planet: "Coruscant", quote: "A Jedi uses the Force for knowledge and defense, never for attack.", droid: "GH-7", vehicle: "Sith Infiltrator"},
  {character: "Kylo Ren", planet: "Mustafar", quote: "Fear is the path to the dark side... fear leads to anger... anger leads to hate... hate leads to suffering.", droid: "B1", vehicle: "Imperial Star Destroyer"},
  {character: "Mace Windu", planet: "Endor", quote: "A Jedi uses the Force for knowledge and defense, never for attack.", droid: "LM-432", vehicle: "Trade Federation Battleship"},
  {character: "Qui-Gon Jinn", planet: "Sullust", quote: "I find your lack of faith disturbing.", droid: "B2-RP", vehicle: "Imperial Star Destroyer"},
  {character: "Anakin Skywalker", planet: "Hosnian Prime", quote: "You know, that little droid is going to cause me a lot of trouble.", droid: "BB-8", vehicle: "ATT Battle Tank"},
  {character: "Poe Dameron", planet: "Lothal", quote: "If you're saying that coming here was a bad idea, I'm starting to agree with you.", droid: "ID9", vehicle: "TIE Bomber"},
  {character: "Darth Vader", planet: "Mustafar", quote: "Aren't you a little short for a Stormtrooper?", droid: "GH-7", vehicle: "V-Wing Fighter"},
  {character: "Jar Jar Binks", planet: "Mustafar", quote: "R2-D2, you know better than to trust a strange computer!", droid: "GH-7", vehicle: "Gungan Bongo Submarine"},
  {character: "Sebulba", planet: "Sullust", quote: "Aren't you a little short for a Stormtrooper?", droid: "ASP", vehicle: "Speeder Bike"},
  {character: "Jango Fett", planet: "Lothal", quote: "It's not impossible. I used to bullseye womp rats in my T-16 back home, they're not much bigger than two meters.", droid: "GH-7", vehicle: "Republic Cruiser"},
  {character: "Watto", planet: "Endor", quote: "Wars not make one great.", droid: "2-1B", vehicle: "Flash Speeder"},
  {character: "Chewbacca", planet: "Mustafar", quote: "R2-D2, you know better than to trust a strange computer!", droid: "NR-N99", vehicle: "Naboo N-1 Starfighter"},
  {character: "Sebulba", planet: "Sullust", quote: "Adventure. Excitement. A Jedi craves not these things.", droid: "BD-3000", vehicle: "X-Wing Fighter"},
  {character: "Poe Dameron", planet: "Hoth", quote: "Do. Or do not. There is no try.", droid: "R2-Q5", vehicle: "Gungan Bongo Submarine"},
  {character: "Kylo Ren", planet: "Dagobah", quote: "That is why you fail.", droid: "11-4D", vehicle: "ATT Battle Tank"},
  {character: "Jango Fett", planet: "Lothal", quote: "You will never find a more wretched hive of scum and villainy. We must be cautious.", droid: "B4-D4", vehicle: "Sith Infiltrator"},
  {character: "Qui-Gon Jinn", planet: "Utapau", quote: "You will never find a more wretched hive of scum and villainy. We must be cautious.", droid: "BD-3000", vehicle: "Sith Infiltrator"},
  {character: "Darth Caedus", planet: "Utapau", quote: "If they follow standard Imperial procedure, they'll dump their garbage before they go to light-speed.", droid: "B4-D4", vehicle: "V-Wing Fighter"},
  {character: "Darth Caedus", planet: "Hoth", quote: "You know, that little droid is going to cause me a lot of trouble.", droid: "327-T", vehicle: "AT-AT Walker"},
  {character: "Bail Organa", planet: "Kamino", quote: "If you're saying that coming here was a bad idea, I'm starting to agree with you.", droid: "4-LOM", vehicle: "AT-AT Walker"},
  {character: "Jango Fett", planet: "Alderaan", quote: "You will never find a more wretched hive of scum and villainy. We must be cautious.", droid: "B2-RP", vehicle: "AT-ST Walker"},
  {character: "Obi-Wan Kenobi", planet: "Hosnian Prime", quote: "It's not impossible. I used to bullseye womp rats in my T-16 back home, they're not much bigger than two meters.", droid: "BB-8", vehicle: "ATT Battle Tank"},
  {character: "Qui-Gon Jinn", planet: "Geonosis", quote: "I have a bad feeling about this.", droid: "4-LOM", vehicle: "Trade Federation Battleship"},
  {character: "Qui-Gon Jinn", planet: "Bespin", quote: "You will never find a more wretched hive of scum and villainy. We must be cautious.", droid: "B2-RP", vehicle: "Trade Federation Battleship"},
  {character: "Padme Amidala", planet: "Takodana", quote: "That is why you fail.", droid: "2-1B", vehicle: "ATT Battle Tank"},
  {character: "Darth Caedus", planet: "Naboo", quote: "Only at the end do you realize the power of the Dark Side.", droid: "FA-4", vehicle: "V-Wing Fighter"},
  {character: "Nute Gunray", planet: "Dagobah", quote: "If you're saying that coming here was a bad idea, I'm starting to agree with you.", droid: "ASP", vehicle: "Millennium Falcon"},
  {character: "Watto", planet: "Bespin", quote: "No reward is worth this.", droid: "ASP", vehicle: "Trade Federation Battleship"},
  {character: "Borvo the Hutt", planet: "Coruscant", quote: "Strike me down, and I will become more powerful than you could possibly imagine.", droid: "BD-3000", vehicle: "Sith Infiltrator"},
  {character: "Lando Calrissian", planet: "Hoth", quote: "It's not impossible. I used to bullseye womp rats in my T-16 back home, they're not much bigger than two meters.", droid: "327-T", vehicle: "AT-ST Walker"}
])
